creation_rules:
  - path_regex: .env.*
    age: age16l82x0fklesfta6660uj9ew9rdqeev279vhgqdymaaz79thlaa6qxz5as3, age16axfpq5apt90tdhpw7m3chnjd7t8ayc53v2q30a73l0f76qyv9aqzrntcz, age15jf5rp5p55mmud726ut0m096mvcsxltza3vj7m0yu4j6addxvgpqava45d
